import tkinter
top = tkinter.Tk()
board = tkinter.Frame (top)
ax = tkinter.Button (top,text='',width=10,height=5)
ay = tkinter.Button (top,text='',width=10,height=5)
az = tkinter.Button (top,text='',width=10,height=5)
bx = tkinter.Button (top,text='',width=10,height=5)
by = tkinter.Button (top,text='',width=10,height=5)
bz = tkinter.Button (top,text='',width=10,height=5)
cx = tkinter.Button (top,text='',width=10,height=5)
cy = tkinter.Button (top,text='',width=10,height=5)
cz = tkinter.Button (top,text='',width=10,height=5)
ax.pack()
ay.pack()
az.pack()
bx.pack()
by.pack()
bz.pack()
cx.pack()
cy.pack()
cz.pack()
top.mainloop()